version: "2"

services:
  namenode:
    image: oliverhu/hadoop-namenode
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: oliverhu/hadoop-resourcemanager:latest
    container_name: resourcemanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env

  historyserver:
    image: oliverhu/hadoop-historyserver:latest
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: oliverhu/hadoop-nodemanager:latest
    container_name: nodemanager1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env

  datanode1:
    image: oliverhu/hadoop-datanode:latest
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./hadoop.env

  datanode2:
    image: oliverhu/hadoop-datanode:latest
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./hadoop.env

  datanode3:
    image: oliverhu/hadoop-datanode:latest
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
